# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketSanta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketSanta
 
  pod 'SwiftGifOrigin'

  target 'PocketSantaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
